const roles = {
  GLOBAL_MOBILE_COUNSELOR: "GLOBAL_MOBILE_COUNSELOR",
  ROLE_UNMASK_CREDITCARD: "ROLE_UNMASK_CREDITCARD",
  ROLE_CLIENT_TRAVELER_MAINTAINER: "ROLE_CLIENT_TRAVELER_MAINTAINER",
};

export default roles;
